# Generated by Django 3.1.7 on 2021-04-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kafkaDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
